/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts,scss}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary': 'var(--color-on-primary)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'surface-tint': 'var(--color-surface-tint)',
        secondary: 'var(--color-secondary)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary': 'var(--color-on-secondary)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        tertiary: 'var(--color-tertiary)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        background: 'var(--color-background)',
        'on-background': 'var(--color-on-background)',
        surface: 'var(--color-surface)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-variant': 'var(--color-surface-variant)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        error: 'var(--color-error)',
        'error-container': 'var(--color-error-container)',
        'on-error': 'var(--color-on-error)',
        'on-error-container': 'var(--color-on-error-container)',
        'success-green': 'var(--color-success)',
        'warning-orange': 'var(--color-warning)',
        'danger-red': 'var(--color-danger)',
        'card-border': 'var(--color-card-border)',
        provenance: 'var(--color-provenance)',
        'provenance-container': 'var(--color-provenance-container)',
        'on-provenance': 'var(--color-on-provenance)',
        'on-provenance-container': 'var(--color-on-provenance-container)',
      },
      fontFamily: {
        sans: ['Work Sans', 'sans-serif'],
        arabic: ['IBM Plex Sans Arabic', 'Work Sans', 'sans-serif'],
        data: ['Work Sans', 'IBM Plex Sans Arabic', 'sans-serif'],
        'body-sm': ['Work Sans', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'body-lg': ['Work Sans', 'sans-serif'],
        'headline-lg': ['Work Sans', 'sans-serif'],
        'headline-lg-mobile': ['Work Sans', 'sans-serif'],
        'headline-md': ['Work Sans', 'sans-serif'],
        'headline-sm': ['Work Sans', 'sans-serif'],
        'title-lg': ['Work Sans', 'sans-serif'],
        'title-md': ['Work Sans', 'sans-serif'],
        'label-lg': ['Work Sans', 'sans-serif'],
        'label-md': ['Work Sans', 'sans-serif'],
        'label-sm': ['Work Sans', 'sans-serif'],
        'display-lg': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg-mobile': [
          '28px',
          { lineHeight: '36px', fontWeight: '600' },
        ],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': [
          '32px',
          {
            lineHeight: '40px',
            letterSpacing: '-0.02em',
            fontWeight: '600',
          },
        ],
        'title-lg': ['22px', { lineHeight: '28px', fontWeight: '500' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'label-lg': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' },
        ],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-sm': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' },
        ],
        'display-lg': [
          '57px',
          {
            lineHeight: '64px',
            letterSpacing: '-0.25px',
            fontWeight: '600',
          },
        ],
        /* Decision figures (SENIOR_DESIGN_SYSTEM Data / Data-sm) */
        data: [
          '28px',
          {
            lineHeight: '1.1',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
        'data-lg': [
          '36px',
          {
            lineHeight: '1.1',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
        'data-sm': [
          '14px',
          {
            lineHeight: '1.2',
            letterSpacing: '-0.01em',
            fontWeight: '600',
          },
        ],
      },
      borderRadius: {
        DEFAULT: 'var(--radius-sm)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        login: 'var(--shadow-login)',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        base: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        unit: 'var(--space-unit)',
        gutter: 'var(--space-gutter)',
        'margin-desktop': 'var(--space-margin-desktop)',
        'margin-mobile': 'var(--space-margin-mobile)',
        'sidebar-width': 'var(--sidebar-width)',
      },
      transitionDuration: {
        DEFAULT: '150ms',
      },
    },
  },
  plugins: [],
};
