/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts,scss}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#1B5E20',
        'primary-container': '#1b5e20',
        'on-primary': '#ffffff',
        'on-primary-container': '#90d689',
        'on-primary-fixed': '#002203',
        'on-primary-fixed-variant': '#0c5216',
        'primary-fixed': '#acf4a4',
        'primary-fixed-dim': '#91d78a',
        'inverse-primary': '#91d78a',
        'surface-tint': '#2a6b2c',
        secondary: '#1b6d24',
        'secondary-container': '#a0f399',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#217128',
        'on-secondary-fixed': '#002204',
        'on-secondary-fixed-variant': '#005312',
        'secondary-fixed': '#a3f69c',
        'secondary-fixed-dim': '#88d982',
        tertiary: '#00460e',
        'tertiary-container': '#006017',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#77db76',
        'on-tertiary-fixed': '#002204',
        'on-tertiary-fixed-variant': '#005313',
        'tertiary-fixed': '#94f990',
        'tertiary-fixed-dim': '#78dc77',
        background: '#fcf9f8',
        'on-background': '#1b1c1c',
        surface: '#fcf9f8',
        'surface-bright': '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-variant': '#e5e2e1',
        'surface-container': '#f0eded',
        'surface-container-low': '#f6f3f2',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#41493e',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f3f0ef',
        outline: '#717a6d',
        'outline-variant': '#c0c9bb',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'success-green': '#1B5E20',
        'warning-orange': '#E65100',
        'danger-red': '#C62828',
        'card-border': '#C8E6C9',
      },
      fontFamily: {
        sans: ['Work Sans', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'body-lg': ['Work Sans', 'sans-serif'],
        'headline-lg': ['Work Sans', 'sans-serif'],
        'headline-lg-mobile': ['Work Sans', 'sans-serif'],
        'headline-md': ['Work Sans', 'sans-serif'],
        'headline-sm': ['Work Sans', 'sans-serif'],
        'label-md': ['Work Sans', 'sans-serif'],
        'label-sm': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': [
          '24px',
          { lineHeight: '32px', fontWeight: '600' },
        ],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': [
          '30px',
          {
            lineHeight: '38px',
            letterSpacing: '-0.02em',
            fontWeight: '600',
          },
        ],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-sm': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' },
        ],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        base: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        gutter: '24px',
        'margin-desktop': '32px',
        'margin-mobile': '16px',
      },
    },
  },
  plugins: [],
};
